# **PYTHON 8 MATRIZES NUMÉRICAS**

### **TÓPICOS A ESTUDAR:**

- NumPy
    - O que é
    - numpy array
    - Exemplos<br><br>
- Comandos básicos
    - Sintaxe
    - Exemplos<br><br>
- Tarefa

-----------------------------------------

## NUMPY (NUMERICAL PYTHON)

**O QUE É**<br>
- É uma biblioteca open-source muito usada na área de Ciência e Engenharia. NumPy é usado amplamente com outras bibliotecas de manipulação de dados, como Pandas, scikit-learn, Matplotlib, entre muitas outras. Ainda, contém estruturas de dados multidimensionais e matriciais, fornecendo **objetos** com sequências **homogêneas** de matriz n-dimensional e métodos para manipulação em cima dos dados.
- Também possui funções para trabalhar no domínio da álgebra linear, transformada de Fourier e matrizes.
<br>

**POR QUE USAR?**<br>
- Em Python temos listas que servem o propósito de matrizes, mas que são lentas de processar, e NumPy pretende fornecer um objecto de matriz que é até 50x mais rápido do que as listas Python tradicionais.
<br>

**ndarray**<br>
- O objecto de matriz em NumPy é chamado `ndarray`, fornece muitas funções de suporte que tornam o trabalho com `ndarray` muito fácil.
- Um `vetor` é um array de uma dimensão, enquanto que uma matriz é um `array` de duas dimensões, e para os `arrays` de três ou mais dimensões é chamado comumente de tensor.

**EXEMPLO**<br>

In [ ]:
import numpy as np
array1 = np.array([0,1,2,3,4])
array2 = np.array([[0,1,2,3,4], [5,6,7,8,9]])

-----------------------------------------

## COMANDOS BÁSICOS

**ATRIBUTO DE NDARRAY**<br>
- O número de dimensões e elementos do array é definido no seu `shape`. O `shape` é uma tupla de números inteiros não negativos que especificam o tamanho de cada dimensão.
- Em NumPy, as dimensões são chamadas de `axes` (eixos).
<br>

**SINTAXE**<br>
```
np.array().shape # retorna o shape do array
```
<br><br>

**ALOCAR UM ARRAY NA MEMÓRIA**<br>
- Partir de uma lista definida
<br>

**SINTAXE**<br>
```
nome = np.array(lista n-dimensões)
```
<br>

- Array preenchido de zeros
<br>

**SINTAXE**<br>
```
nome = np.zeros(shape)
```
<br>

- Array preenchido de um
<br>

**SINTAXE**<br>
```
nome = np.ones(shape)
```
<br>

- Array vazio (usar essa função em vezes de `zeros` é velocidade)
<br>

**SINTAXE**<br>
```
nome = np.empty(shape)
```
<br>

- Array a partir de um `range`
<br>

**SINTAXE**<br>
```
nome = np.arange(start, stop, step)
```
<br>

- Matriz com valores espaçados linearmente num intervalo especifico
<br>

**SINTAXE**<br>
```
nome = np.linspace(start, stop, num)
```
<br>

**EXEMPLO**<br>

In [7]:
import numpy as np

array1 = np.array([0,1,2,3,4])
array1

array([0, 1, 2, 3, 4])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.linspace(0, 5, num=5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

-----------------------------------------

## TAREFA

In [ ]:
""" ESCREVA UM ALGORITMO QUE RECEBA UM VALOR E RETORNA O NOME DA CHAVE DO DICIONÁRIO QUE CONTENHA AQUELE VALOR """

dic = dict(bateria=12, energia=110, hello='world', corrente=2, tipo='dicionário')
valor = 2

# Escreva seu código abaixo


-----------------------------------------