# **PYTHON 8 MATRIZES NUMÉRICAS (parte 1)**

### **TÓPICOS A ESTUDAR:**

- NumPy
    - O que é
    - numpy array
    - Exemplos<br><br>
- Comandos básicos
    - Sintaxe
    - Exemplos<br><br>
- Tarefa

-----------------------------------------

## NUMPY (NUMERICAL PYTHON)

**O QUE É**<br>
- É uma biblioteca open-source muito usada na área de Ciência e Engenharia. NumPy é usado amplamente com outras bibliotecas de manipulação de dados, como Pandas, scikit-learn, Matplotlib, entre muitas outras. Ainda, contém estruturas de dados multidimensionais e matriciais, fornecendo **objetos** com sequências **homogêneas** de matriz n-dimensional e métodos para manipulação em cima dos dados.
- Também possui funções para trabalhar no domínio da álgebra linear, transformada de Fourier e matrizes.
<br>

**POR QUE USAR?**<br>
- Em Python temos listas que servem o propósito de matrizes, mas que são lentas de processar, e NumPy pretende fornecer um objecto de matriz que é até 50x mais rápido do que as listas Python tradicionais.
<br>

**ndarray**<br>
- O objecto de matriz em NumPy é chamado `ndarray`, fornece muitas funções de suporte que tornam o trabalho com `ndarray` muito fácil.
- Um `vetor` é um array de uma dimensão, enquanto que uma matriz é um `array` de duas dimensões, e para os `arrays` de três ou mais dimensões é chamado comumente de tensor.

**EXEMPLO**<br>

In [ ]:
import numpy as np
array1 = np.array([0,1,2,3,4])
array2 = np.array([[0,1,2,3,4], [5,6,7,8,9]])

-----------------------------------------

## COMANDOS BÁSICOS

**ATRIBUTO DE NDARRAY**<br>
- O número de dimensões e elementos do array é definido no seu `shape`. O `shape` é uma tupla de números inteiros não negativos que especificam o tamanho de cada dimensão.
- Em NumPy, as dimensões são chamadas de `axes` (eixos).
<br>

**SINTAXE**<br>
```
np.array().shape # retorna o shape do array
np.array().ndim # retorna o número de dimensões do array
np.array().size # retorna quantidade de elementos tem no array
```
<br>

**ALOCAR UM ARRAY NA MEMÓRIA**<br>
- `np.array(lista n-dimensões)`: Partir de uma lista definida
- `np.zeros(shape)`: Array preenchido de zeros
- `np.ones(shape)`: Array preenchido de um
- `np.empty(shape)`: Array vazio (usar essa função em vezes de `zeros` é velocidade)
- `np.arange(start, stop, step)`: Array a partir de um `range`
- `np.linspace(start, stop, num)`: Matriz com valores espaçados linearmente num intervalo especifico
<br>

**ADICIONAR E ORGANIZAR ARRAY**<br>
- `np.sort(np.array())`: Organiza a lista de argumento em ordem crescente (retorna uma cópia do array)
- `np.concatenate((np.array(), np.array()))`: Array preenchido de zeros
* Há outras funções para organizar arrays (argsort, lexsort, searchsort, ...)
<br>

**RESHAPE**<br>
- `np.array().reshape()`: Aplica um reshape no array sem alterar os dados
<br>

**ADICIONAR AXIS**<br>
- `np.array()[np.newaxis, :]`: Adiciona uma linha no array
- `np.array()[:, np.newaxis]`: Adiciona uma coluna no array
- `np.expand_dims(array, axis)`: Adiciona um linha (axis=0) ou coluna (axis=1) 
<br>

**INDEXAÇÃO E SLICE**<br>
- Mesmo mecânismo de indexação e slice que as lista em Python tem
<br>

**EXEMPLO**<br>

In [14]:
import numpy as np

array1 = np.array([[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14]])
print(array1, '\n')
print('shape:',array1.shape)
print('ndim:',array1.ndim)
print('size:',array1.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

shape: (3, 5)
ndim: 2
size: 15


In [15]:
array1 = np.array([0,1,2,3,4])
array1

array([0, 1, 2, 3, 4])

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
np.linspace(0, 5, num=5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [8]:
array2 = np.array([4,2,9,8,7,6,3])
np.sort(array1)

array([2, 3, 4, 6, 7, 8, 9])

In [9]:
np.concatenate((array2, array1))

array([4, 2, 9, 8, 7, 6, 3, 4, 2, 9, 8, 7, 6, 3])

In [27]:
array1 = np.linspace(0,49)
print(array1)
print('shape:', array1.shape, '\n')

array1 = array1.reshape(2,5,5)
print(array1)
print('shape:', array1.shape)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
shape: (50,) 

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]]
shape: (2, 5, 5)


In [28]:
array1 = np.array([0,1,2,3,4])
array1 = array1[np.newaxis, :]
array1

array([[0, 1, 2, 3, 4]])

In [29]:
array1 = np.array([0,1,2,3,4])
array1 = array1[:, np.newaxis]
array1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [33]:
array1 = np.array([0, 1, 2, 3, 4])
print('shape:', array1.shape)

array1 = np.expand_dims(array1, axis=0)
print('shape:', array1.shape)

shape: (5,)
shape: (1, 5)


In [34]:
array1 = np.array([0, 1, 2, 3, 4])
print('shape:', array1.shape)

array1 = np.expand_dims(array1, axis=1)
print('shape:', array1.shape)

shape: (5,)
shape: (5, 1)


In [38]:
array1 = np.array([[0, 1, 2, 3, 4], [5,6,7,8,9]])
print(array1[0])
print(array1[:-1])
print(array1[1, 1:4])
print(array1[array1 >= 3])

[0 1 2 3 4]
[[0 1 2 3 4]]
[6 7 8]
[3 4 5 6 7 8 9]


-----------------------------------------

## TAREFA

In [ ]:
"""  """

# Escreva seu código abaixo


-----------------------------------------