# **PYTHON 9 MATRIZES NUMÉRICAS (parte 2)**

### **TÓPICOS A ESTUDAR:**

- Operaçãoes com matrizes
    - Sintaxe
    - Exemplos<br><br>
- Salvar e carregar dados
    - Sintaxe
    - Exemplos<br><br>
- Tarefa

-----------------------------------------

## OPERAÇÕES COM MATRIZES

**OPERAÇÕES BÁSICAS**<br>
- `np.array() + np.array()`: Soma o elemento da linha i e coluna j com o elemento da mesmo posição da outra matriz
- `np.array() - np.array()`: Subtrai o elemento da linha i e coluna j com o elemento da mesmo posição da outra matriz
- `np.array() * np.array()`: Multiplica o elemento da linha i e coluna j com o elemento da mesmo posição da outra matriz
- `np.array() / np.array()`: Divide o elemento da linha i e coluna j com o elemento da mesmo posição da outra matriz

\* É possível fazer essas operações com arrays de tamanhos diferentes, porém apenas se o array tiver uma coluna ou uma linha<br>

- `np.array() + x`: Soma todos os elementos da matriz com o valor de `x` (qualquer operação)
<br>

**MÉTODOS ÚTEIS COM ARRAYS**<br>
- `np.array().max()`: Retorna o maior valor no array
- `np.array().min()`: Retorna o menor valor no array
- `np.array().sum()`: Retorna a soma de todos os elementos do array
* Há outras funções para organizar arrays (argsort, lexsort, searchsort, ...)
<br>

**MATRIZ TRANSPOSTA**<br>
- `np.array().transpose()`: Retorna a transposta da matriz
- `np.array().T`: Retorna a transposta da matriz
<br>

**MATRIZ REVERSA**<br>
- `np.flip(np.array())`: Retorna a matriz com os valores reversos
- `np.flip(np.array(), axis=0)`: Retorna a matriz com os valores reversos apenas nas linhas
- `np.flip(np.array(), axis=1)`: Retorna a matriz com os valores reversos apenas nas colunas

**MATRIZ INVERSA**<br>
- `np.linalg.inv(np.array())`: Retorna a matriz inversa

**REMOVER DIMENSÕES**<br>
- `np.array().flatten()`: Retorna a matriz menos 1 dimensão sem alterar os valores

**MATHEMATICAL FORMULAS**
- A facilidade da implementação de fórmulas matemáticas que trabalham com matrizes é uma das coisas que torna NumPy tão utilizado pela comunidade científica.
- Utilizar as funções de operações matemáticas do NumPy
<br>

**EXEMPLO**<br>

In [11]:
# diferença de multiplicação de matrizes
array1 = np.array([[1,2], [3,4]])
print(array1, '\n')
print(array1@array1, '\n') #.dot(), multiplicação matricial
print(array1*array1)

[[1 2]
 [3 4]] 

[[ 7 10]
 [15 22]] 

[[ 1  4]
 [ 9 16]]


In [14]:
import numpy as np

array1 = np.array([[0,1,2,3,4], [5,6,7,8,9]])
array2 = np.array([[0,1,2,3,4], [5,6,7,8,9]])
array1 + array2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [25]:
array1 = np.array([[0,1,2,3,4], [5,6,7,8,9]])
array1 * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [4]:
print(array1.max())
print(array1.min())
print(array1.sum())

9
0
45


In [12]:
print(array1.transpose(), '\n')
print(array1.T)

[[1 3]
 [2 4]] 

[[1 3]
 [2 4]]


In [19]:
print(array1, '\n')
print(np.flip(array1), '\n')
print(np.flip(array1, axis=0), '\n')
print(np.flip(array1, axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[9 8 7 6 5]
 [4 3 2 1 0]] 

[[5 6 7 8 9]
 [0 1 2 3 4]] 

[[4 3 2 1 0]
 [9 8 7 6 5]]


In [21]:
array2 = np.array([[2,3], [0,1]])
np.linalg.inv(array2)

array([[ 0.5, -1.5],
       [ 0. ,  1. ]])

In [23]:
array1 = np.array([[[[0,1,2,3,5]]]])
print(array1.ndim)
print(array1.flatten().ndim)

4
1


In [27]:
MeanSquaredError = 1/array1.size * np.sum(np.square(array1 - (array1+1)))
MeanSquaredError

1.0

-----------------------------------------

## SALVAR E CARREGAR DADOS

- `np.save('file.npy', np.array())`: Salva o array pelo caminho passado como `.npy`
- `np.load('file.npy')`: Retorna o arquivo lido como um array

\* É possível também ler e salvar CSV's com NumPy:
- `np.savetxt('file.csv', np.array())`: Salva o array pelo caminho passado como `.csv`
- `np.loadtxt('file.csv')`: Retorna o arquivo `.csv` como um array
<br>

**EXEMPLO**<br>

In [31]:
import numpy as np

array1 = np.array([[0,1,2,3,4], [5,6,7,8,9]])
np.save('Data/data.npy', array1)

In [32]:
data = np.load('Data/data.npy')
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

-----------------------------------------